const state = {
    codigo: '',
    nome: '',
    codigoPostal: '',
    morada: '',
    contribuinte: '',
    contato: '',
    products: [
      {
        codigo: "101 001",
        count: 0,
        nome: "Equilibrium Sh. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "102 001",
        count: 0,
        nome: "Equilibrium Cond. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "101 003",
        count: 0,
        nome: "Blond Sh. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "102 003",
        count: 0,
        nome: "Blond Cond. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "101 006",
        count: 0,
        nome: "Miracle Sh. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "102 006",
        count: 0,
        nome: "Miracle Cond. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "101 007",
        count: 0,
        nome: "Sh. Therapy 300ml",
        price: 10.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "101 038",
        count: 0,
        nome: "Curly Sh. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "102 036",
        count: 0,
        nome: "Curly Cond. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "101 038",
        count: 0,
        nome: "Infusion Sh. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "102 036",
        count: 0,
        nome: "Infusion Cond. 300ml",
        price: 8.5,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "102 035",
        count: 0,
        nome: "Miracle Summer Cond. 300ml",
        price: 9.0,
        linha: "HOMECARE",
        subLinha: "DAILY CARE",
        estoque:true,
      },
      {
        codigo: "103 010",
        count: 0,
        nome: "Blond Mask 180g",
        price: 13.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "103 003",
        count: 0,
        nome: "Miracle Mask 180g",
        price: 13.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "103 016",
        count: 0,
        nome: "Net Mask 550g",
        price: 19.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "104 012",
        count: 0,
        nome: "Night Spa Serum 250ml",
        price: 24.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "104 002",
        count: 0,
        nome: "Deluxe Prime 260ml",
        price: 17.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "104 028",
        count: 0,
        nome: "Deluxe Prime Blond 260ml",
        price: 19.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "104 040",
        count: 0,
        nome: "Deluxe Prime Summer 260ml",
        price: 19.0,
        linha: "HOMECARE",
        subLinha: "WEEKLY CARE",
        estoque:true,
      },
      {
        codigo: "305 024",
        count: 0,
        nome: "Hair Protector 250ml",
        price: 12.0,
        linha: "HOMECARE",
        subLinha: "FINISH",
        estoque:true,
      },
      {
        codigo: "305 032",
        count: 0,
        nome: "Curly Fix 250ml",
        price: 12.0,
        linha: "HOMECARE",
        subLinha: "FINISH",
        estoque:true,
      },
      {
        codigo: "313 012",
        count: 0,
        nome: "Fluid Fix 250ml",
        price: 12.0,
        linha: "HOMECARE",
        subLinha: "FINISH",
        estoque:true,
      },
      {
        codigo: "305 023",
        count: 0,
        nome: "Instant Repair 45ml",
        price: 12.0,
        linha: "HOMECARE",
        subLinha: "FINISH",
        estoque:true,
      },
      {
        codigo: "211 044",
        count: 0,
        nome: "Kit Fast Repair",
        price: 101.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "201 011",
        count: 0,
        nome: "Bidimensional Sh. 1000ml",
        price: 33.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "204 006",
        count: 0,
        nome: "Lipidic 650ml",
        price: 28.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "203 006",
        count: 0,
        nome: "Intensive Nutrition 1000ml",
        price: 33.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "201 012",
        count: 0,
        nome: "Clarifying Sh. 1000ml",
        price: 33.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "205 011",
        count: 0,
        nome: "Amino Miracle 225ml",
        price: 20.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "201 027",
        count: 0,
        nome: "Therapy Sh.",
        price: 28.0,
        linha: "PROFISSIONAL",
        subLinha: "BACK BAR ESSENTIALS - MIRACLE",
        estoque:true,
      },
      {
        codigo: "204 022",
        count: 0,
        nome: "8x Powder 200g",
        price: 59.0,
        linha: "PROFISSIONAL",
        subLinha: "PERFECT BLOND",
        estoque:true,
      },
      {
        codigo: "409 006",
        count: 0,
        nome: "Air Libre 500g",
        price: 23.0,
        linha: "PROFISSIONAL",
        subLinha: "PERFECT BLOND",
        estoque:true,
      },
      {
        codigo: "409 007",
        count: 0,
        nome: "Blanc Blond 500g",
        price: 23.0,
        linha: "PROFISSIONAL",
        subLinha: "PERFECT BLOND",
        estoque:true,
      },
      {
        codigo: "k.415000",
        count: 0,
        nome: "Papel Laminado Longo 50 x 11",
        price: 28.0,
        linha: "PROFISSIONAL",
        subLinha: "PERFECT BLOND",
        estoque:true,
      },
      {
        codigo: "k.416000",
        count: 0,
        nome: "Papel Laminado Curto 25 x 11",
        price: 28.0,
        linha: "PROFISSIONAL",
        subLinha: "PERFECT BLOND",
        estoque:true,
      },
      {
        codigo: "204 025",
        count: 0,
        nome: "K. Recovery 650ml",
        price: 59.0,
        linha: "PROFISSIONAL",
        subLinha: "RECOVERY ESSENTIALS",
        estoque:true,
      },
      {
        codigo: "203 008",
        count: 0,
        nome: "Infusion 650ml",
        price: 51.0,
        linha: "PROFISSIONAL",
        subLinha: "RECOVERY ESSENTIALS",
        estoque:true,
      },
      {
        codigo: "210 010",
        count: 0,
        nome: "High Liss 650ml",
        price: 70.0,
        linha: "PROFISSIONAL",
        subLinha: "SMOOTHING TREATMENT",
        estoque:true,
      },
      {
        codigo: "210 011",
        count: 0,
        nome: "High Liss Blond 650ml",
        price: 75.0,
        linha: "PROFISSIONAL",
        subLinha: "SMOOTHING TREATMENT",
        estoque:true,
      },
    ],
    dados: [
      {
        codigo: 1234,
        nome: "",
        codigoPostal: "",
        morada: "",
        contribuinte: "",
        contato: "",
        comercial: "",
      },
    ],
  };

  module.exports = state